# Generated by Django 3.2.13 on 2022-05-22 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xrp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('open', models.DecimalField(decimal_places=3, max_digits=10)),
                ('high', models.DecimalField(decimal_places=3, max_digits=10)),
                ('low', models.DecimalField(decimal_places=3, max_digits=10)),
                ('close', models.DecimalField(decimal_places=3, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=15)),
                ('market_cap', models.DecimalField(db_column='market cap', decimal_places=3, max_digits=15)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
