version: '3'

services:
  sleek-airflow:
    image: sleek-airflow:latest-v1.3

    volumes:
      - ./airflow:/opt/airflow
      #- ./airflow/dags:/opt/airflow/dags
      #- ./airflow/logs:/opt/airflow/logs
      #- ./airflow/airflow.cfg:/opt/airflow/airflow.cfg
    ports:
      - "8080:8080"

    command: airflow standalone